### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by dianecw** [cs160LizardSquad/alfridge#1]
**Homepage**
- [x] Update compartment names when simulator is updated
- [ ] Decide on how to set the compartment name (also implement this)

**Compartment View**
- [x] Make dynamic - update with the simulator

**NavBar**
- [ ] Highlight tab when it is selected

**Items**
- [x] Implement items view

**Grocery Lists**
- [x] Implement grocery lists view

**Settings**
- [ ] Implement settings

**Notifications**
- [ ] Implement notifications

**Comment by dianecw** [comment]
Now putting these onto individual issues.
